services:
  mysql_db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
    container_name: mysql_db
    networks:
      - octaltask_network
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  api-gateway:
    build:
      context: ./api-gateway
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
    container_name: api-gateway
    networks:
      - octaltask_network
    ports:
      - "80:3000"

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    networks:
      - octaltask_network
    depends_on:
      - mysql_db

  file-service:
    build:
      context: ./file-service
    container_name: file-service
    networks:
      - octaltask_network
    depends_on:
      - mysql_db

  task-service:
    build:
      context: ./task-service
    container_name: task-service
    networks:
      - octaltask_network
    depends_on:
      - mysql_db

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    networks:
      - octaltask_network
    depends_on:
      - mysql_db


volumes:
  mysql-data:



networks:
  octaltask_network:
    driver: bridge